ConnectionStrings: 
  AppDbContext: "Data Source=DBOPRCNSUNIDESA.andreani.com.ar;Initial Catalog=OPERACIONES_UNI;Persist Security Info=True;User ID=User_Operaciones_Uni_desa;Password=SDlqtFq7kZXLK1dQ18wN;TrustServerCertificate=True"